### PR TITLE
Changed title from Previous Tasks to Previously Viewed Tasks

### PR DESCRIPTION
**Pull request by petemoore**
I didn't understand what "Previous Tasks" meant, so I reworded it.

### CODE REVIEW

**Comment by petemoore** [comment]
Thanks @jonasfj. Shouldn't this auto-deploy on merge?

**Comment by petemoore** [comment]
I see a (travis failure)[https://travis-ci.org/taskcluster/taskcluster-tools/builds/122331413#L692] :/

**Comment by jonasfj** [comment]
Yeah due to issues with docker-exec-websocket-server
Den 12. apr. 2016 12.12 AM skrev "Pete Moore" <notifications@github.com>:

**Comment by petemoore** [comment]
@jonasfj I just rebuilt, and hit same issue. How do we fix this?

**Comment by jonasfj** [comment]
lock the version to `1.1.0` rather than `^1.1.0`.

**Comment by petemoore** [comment]
Created PR #90 for the fix. Thanks!

**Pull request merged**
