### PR TITLE
Add kill button to aws-provisioner page

### PR DESCRIPTION
**Pull request by helfi92**

### CODE REVIEW

**Comment by helfi92** [comment]
Added an action column to terminate ec2 instances.

screen shot 2017-11-13 at 12 49 58 pm

**Comment by helfi92** [comment]
I'm planning to make use of the [Notification](https://github.com/taskcluster/taskcluster-tools/pull/376/files#diff-c5ad988df336fa9d230b60faf8f65e3d) component once it gets merged to notify the user when an action finishes running. This shouldn't stop the pull-request from being merged, however.

**Comment by jhford** [comment]
Looks cool to me!  A button for kill all of a specific worker type would also be great too using the ` route: '/worker-types/:workerType/resources'` endpoint.

**Comment by helfi92** [comment]
@jhford Sounds good, will add that in a different PR. Thanks!

**Pull request merged**
