### PR TITLE
Improving titles of inspector tabs

### PR DESCRIPTION
**Pull request by eliperelman**
Attempting to improve the titles of the inspector tabs so its a *little* clearer about the hierarchy.

tabs

Thoughts @djmitche?

### CODE REVIEW

**Comment by djmitche** [comment]
It's an improvement :)

**Comment by eliperelman** [comment]
@djmitche if you have ideas for other phrasing I'm open. Just no layout changes. 😄

**Comment by djmitche** [comment]
If limited to phrasing changes, this is as good as I can imagine..

**Comment by eliperelman** [comment]
OK then, we'll ship this for now.

**Pull request merged**
