### PR TITLE
Upgraded to react.js 0.14, newer react-bootstrap and lodash

### PR DESCRIPTION
**Pull request by jonasfj**
@imbstack figured I would send a review your way :)

This one just a refactor to upgrade react, react-bootstrap, lodash and few other libraries...
I've tested it reasonably, the rest of bugs we can fix when we find them.

You can pretty much rubber stamp it, unless you see any obvious issues... it's mostly just a lot of clean up and few fixes and lodash had some annoying changes..

### CODE REVIEW

**Comment by jonasfj** [comment]
note, I think we can disregard circleci issues, we should move deployment to travis anyways... they are pretty good now...

**Comment by jonasfj** [comment]
ah, purging cache did the trick...

**Comment by jonasfj** [comment]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1145516

**Comment by imbstack** [comment]
Afaict, this looks good. You have my rubber-stamp of approval. :+1:

**Comment by jonasfj** [comment]
Thanks...

**Pull request merged**
