### PR TITLE
Describe job in task inspector title

### PR DESCRIPTION
**Pull request by wlach**
This resolves https://bugzilla.mozilla.org/show_bug.cgi?id=1252954

### CODE REVIEW

**Comment by wlach** [comment]
@eliperelman @djmitche -- guessing one of you can review this?

**Comment by eliperelman** [comment]
N.b. For clarity, we are already using react-helmet in unified-logviewer so we also want to use it for consistency.

**Comment by wlach** [comment]
That makes sense! I'll give react-helmet a try next week, thanks!

**Comment by wlach** [comment]
@eliperelman Updated to use react-helmet, that is indeed a lot nicer. Please have a look!

**Pull request merged**
