### PR TITLE
Bug 1436421: Edit hooks in YAML instead of JSON

### PR DESCRIPTION
**Pull request by adityac8**
This PR is in reference to the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1436421)
Kindly review the changes.

### CODE REVIEW

**Comment by adityac8** [comment]
Hello, @eliperelman  caught stuck with my end-terms. I will finish this up right now. Sorry for the delay :(

**Comment by helfi92** [comment]
@adityac8 Any chance you want to finish this awesome pull-request :)

**Comment by adityac8** [comment]
Sorry, I won't be able to as I am not able to find the bug which is causing this :disappointed:

**Comment by djmitche** [comment]
Thanks for letting us know!  It's fine to be unable to finish something in open-source, but best to let others know so they can take it on.  I can probably wrap this up.

**Comment by helfi92** [comment]
We will take care of this in taskcluster-web.

**Pull request closed without merging**
