### PR TITLE
Add a taskcluster-branded spinner

### PR DESCRIPTION
**Pull request by imbstack**
I always wanted to see if we could do something like this. Is it nice looking to you? It just replaces the default spinner with an animated tc logo svg that pulses a bit.

Logo is viewable at https://github.com/taskcluster/taskcluster-tools/blob/4c94a7ce21d3797f58a8e089cc860444c5b1b9d4/src/lib/assets/taskcluster-spinner.svg

tests are failing now because of https://github.com/nodejs/nodejs.org/issues/1191 afaict. I'll rerun them tomorrow when that is fixed.

### CODE REVIEW

**Comment by djmitche** [comment]
👍

**Comment by djmitche** [comment]
What if the inside pulsed from blue to gray?

**Comment by imbstack** [comment]
@eliperelman any further thoughts on this? I don't remember what we decided to do now :p

**Comment by eliperelman** [comment]
The light-gray on darker-gray isn't very high contrast. Having some color, or just spinning the original logo would help.

**Comment by imbstack** [comment]
Switched to black+white rather than gray+gray!

**Comment by djmitche** [comment]
I like it!

**Comment by eliperelman** [comment]
Totally agree! This is :fire:!

**Pull request merged**
