### PR TITLE
New auth tool

### PR DESCRIPTION
**Pull request by jonasfj**
New auth tool... still hard coded to use tc-auth-load-test app... for now...

almost ready to merge...

### CODE REVIEW

**Comment by jonasfj** [comment]
@djmitche, if you have any comments on this they are welcome... but UI review isn't high on my list of priorities :)

**Comment by djmitche** [comment]
For those without permissions (which is most people), this is a pretty bad first impression:

screenshot from 2015-10-06 12-16-11

I think it'd be worth intercepting that particular error and displaying a more friendly message:
----
## Permission Denied

This tool is for administrators to add, remove, and update TaskCluster credentials.  You don't have permission to view credentials.

If you would like to set up temporary credentials (with few permissions), click the "Log In" link.  If you have received a set of permanent credentials, add those in the [preferences](https://tools.taskcluster.net/preferences/) tool.
----

**Comment by djmitche** [comment]
Oh, hah, now I see that you've built new tools to replace that, duh.  In my defense, the change is in the last file in the diff (menu.js)

**Comment by djmitche** [comment]
So yeah, this looks good :)

**Comment by jonasfj** [comment]
Yeah, new tools aren't deployed yet... But that's just hitting the merge button...

They currently operate in load-test server so won't do it now...

**Pull request merged**
