### PR TITLE
Bug 1385307 - Show artifact lock icon for logged users

### PR DESCRIPTION
**Pull request by cynthiapereira**
This will replace the `getIconFromMime()` function with the `lock icon`. 

Referred: [Bug 1385307](https://bugzilla.mozilla.org/show_bug.cgi?id=1385307)

### CODE REVIEW

**Comment by djmitche** [comment]
That's the 'one line' I thought it would be :)

**Comment by cynthiapereira** [comment]
I would love to discuss how to improve this and show both cases :)

**Comment by djmitche** [comment]
@eliperelman there was some discussion in the bug about making this more useful for the user -- what do you think?

**Comment by cynthiapereira** [comment]
@eliperelman I updated the PR.

I rollback to display the mime type for private artifacts again and added the lock icon.
Here it will be:
screen shot 2018-02-22 at 16 47 00

**Comment by eliperelman** [comment]
You could add a `locked` property somewhere around here:

https://github.com/taskcluster/taskcluster-tools/pull/444/files#diff-a0dae82bc49a92f8161e2c44ef25b71aR91

**Comment by cynthiapereira** [comment]
You're right about an artifact does not have a `userSession` property, sorry!

So, I made the requested changes, added a `locked: true` property inside the `userSession` conditional for a signed URL, removed the unnecessary part and then take advantage of `map` to render the locked icon.

**Pull request merged**
