### PR TITLE
bug1520857-add many lastfire info

### PR DESCRIPTION
**Pull request by Biboswan**

### CODE REVIEW

**Comment by Biboswan** [comment]
tools
 @djmitche

**Comment by djmitche** [comment]
Could we hide that big wall of JSON behind some kind of click?

I think we will end up going back to make that a rendered markdown error, since I expect InsufficientScopes is the most common kind, so don't worry about parsing the JSON (it might not be valid anyway!)

**Comment by djmitche** [comment]
Let's see what @helfi92 says when he's back!

**Comment by helfi92** [comment]
The tools site will no longer be used soon. I wonder if we should bother with trying to have this functionality in tools. @djmitche thoughts?

**Comment by djmitche** [comment]
I think that's OK.

**Comment by helfi92** [comment]
> I think that's OK.

What do you think is okay? :)

**Comment by djmitche** [comment]
Haha, sorry -- I think it's OK to skip implementing this in tools.

**Pull request closed without merging**
