### PR TITLE
Algolia docs search in navigation

### PR DESCRIPTION
**Pull request by eliperelman**
screen shot 2018-03-13 at 1 39 56 pm

### CODE REVIEW

**Comment by djmitche** [comment]
Hm, should we think twice about running Algolia's (hosted?) JS in a context where we have LocalStorage full of powerful credentials?  I don't know how best to evaluate that..

**Comment by eliperelman** [comment]
Right now trying to get feature parity with docs, so if you're cool with not having docs search, we can delete this.

**Comment by djmitche** [comment]
It seems safer - @imbstack, thoughts?

**Comment by imbstack** [comment]
Yeah, let's remove it for now I guess. It was never all that useful and we can add it back later if we want.

**Comment by eliperelman** [comment]
Works for me.

**Pull request merged**
