### PR TITLE
Allow pasting several scopes into the scope editor

### PR DESCRIPTION
**Pull request by djmitche**
This is a convenience when, for example, setting up new projects.

I could potentially add a tooltip for this, but I don't know if that's more distracting than the feature is worth - what do you think?

### CODE REVIEW

**Comment by jonasfj** [comment]
r+

Although maybe we should hide it behind a check box... Because this prevents us from making scopes with whitespace which is allowed...

Otherwise create feature :)

**Comment by djmitche** [comment]
Ack, you're right -- this should just split on newlines.

**Comment by djmitche** [comment]
OK, updated, and a little bit of extra stuff added

**Comment by djmitche** [comment]
Duh, that's not right either.  Sorry, I forgot to test before pushing!

**Comment by djmitche** [comment]
OK, I reworked it to use a textarea instead.  And actually tested it this time.

**Comment by jonasfj** [comment]
I suspect we would better off using codemirror or ace without line numbers than textarea...
But while this isn't as pretty as what we had before, I think this improves productivity :)

**Pull request merged**
