### PR TITLE
Bug 1281774 - Adjustments to taskview UI to better support more runs

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by eliperelman** [comment]
@jonasfj would you mind looking this over for a review?

**Comment by eliperelman** [comment]
Screenshot of UI changes, along with loaded extra run:

run14

**Comment by gregarndt** [comment]
Awesome Eli!

**Comment by eliperelman** [comment]
@gregarndt 🙇

**Comment by walac** [comment]
\o/

**Comment by jonasfj** [comment]
lol, I didn't know more runs was broken...

r+

**Pull request merged**
