### PR TITLE
Automatically refresh site if remote commit version changes

### PR DESCRIPTION
**Pull request by eliperelman**
Summary:

* Adds a new plugin which outputs a `COMMITHASH` file to the bundle (which would be generated in Heroku)
* Entry point fetches this file every 5 minutes
* Page refreshes if hash has changed

Helps mitigate issues with users keeping tools pages open in their browser with a new version removing old bundles.

### CODE REVIEW

**Comment by djmitche** [comment]
What if this refreshes while I have a textarea full of content?

**Comment by eliperelman** [comment]
@djmitche *poof*

**Comment by djmitche** [comment]
Could we shift to fetch the file on route change (with a 5-minute cache)?  I feel like losing data on a route change is expected, but having a tab silently delete the task definition I've been working on for a half-hour sounds frustrating.

**Comment by djmitche** [comment]
c.f. https://bugzilla.mozilla.org/show_bug.cgi?id=1403575

**Comment by eliperelman** [comment]
Closing as we need to figure out a better state persistence strategy before doing this.

**Pull request closed without merging**
