### PR TITLE
Fixing a few papercuts in the group inspector UI

### PR DESCRIPTION
**Pull request by eliperelman**
@gregarndt maybe this would be an improvement?

### CODE REVIEW

**Comment by jonasfj** [comment]
Nice

**Comment by jonasfj** [comment]
Maybe we should invite some automatic staging site system for each PR.. Reviews like this are more fun that way :)

**Comment by eliperelman** [comment]
That sounds awesome.

**Comment by jonasfj** [comment]
`r+` btw

**Comment by eliperelman** [comment]
Thanks!

**Pull request merged**
