### PR TITLE
Fixed bug...

### PR DESCRIPTION
**Pull request by jonasfj**
merge and it'll deploy in like 10min

### CODE REVIEW

**Comment by gregarndt** [comment]
:+1:

**Comment by garbas** [comment]
just out of curiosity is this is babel bug? or i've used "async () => { ... }" wrong?

**Comment by jonasfj** [comment]
@garbas,
No Babel bug... The async... Thing you wrote is a function that returns a promise.... A function does nothing unless called. Which is all I did :)

**Comment by jonasfj** [comment]
LoadState is a hack I've done in the mixin that allows to get state from a promise object...

**Pull request merged**
