### PR TITLE
Improve usability of Taskcluster Tools [continued]

### PR DESCRIPTION
**Pull request by helfi92**
Continuation of #206

### CODE REVIEW

**Comment by helfi92** [comment]
Work still in progress

**Comment by helfi92** [comment]
To put things into perspective, the two main changes are:

* Removed mixins from the tools website
* Added deep-linking to routes

#### Removed mixins from the tools website
To remove mixins, I augmented each component which previously used mixins with higher-order components.

| Before (mixins) | After (HOC) |
| -------------- | ------------- |
| createTaskClusterMixin | TaskClusterEnhance |
| createWebListenerMixin | CreateWebListener |
| createWatchStateMixin | CreateWatchState |

With higher-order components, components now communicate using event listeners. Each listener is documented in its HOC function signature. The event listeners are the following:

<table>
  <tbody>
    <tr>
      <th>HOC</th>
      <th align="center">Event Listeners</th>
    </tr>
    <tr>
      <td>TaskClusterEnhance</td>
      <td>
        <ul>
          <li>taskcluster-reload</li>
          <li>taskcluster-update</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>CreateWebListener</td>
      <td>
        <ul>
          <li>listener-message</li>
          <li>listener-listening</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td align="center">CreateWatchState</td>
      <td>
        <ul>
          <li>watch-reload</li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

Since most components implement `TaskClusterEnhance`, in order to target specific components when dispatching events, there needs to be a condition check that you will find under `load()` and `onTaskClusterUpdate()`.

```javascript
load(data) {
    if (typeof data === 'object' && data.detail.name && data.detail.name !== this.constructor.name) {
      return;
    }

    // ...
}
```

```javascript
onTaskClusterUpdate({ detail }) {
    if (detail.name !== this.constructor.name) {
      return;
    }

    // ...
}
```
#### Added deep-linking to routes
The tools website now acts as a single page application and handles routing using React-Router v4. I added deep-linking to most components.

**Comment by helfi92** [comment]
2 known issues:
* Running `yarn build` locally takes ~12 minutes to complete.
* Opening the `index.html` after running `yarn build` is showing me a blank screen. I tried removing `neutrino.config.output.publicPath('/');` from the preset but it was still not working. `yarn start` works seamlessly however.

**Comment by djmitche** [comment]
Neutrino 5 also appears to be mostly incomptaible with running a frontend proxy such as https://ngrok.io.

**Pull request merged**
