### PR TITLE
Bug 1440455 resolved- Clear the right panel in the scope expander view when the clean button is clicked

### PR DESCRIPTION
**Pull request by Aditi574**
Clear the right panel in the scope expander view when the clean button is clicked

### CODE REVIEW

**Comment by helfi92** [comment]
@Aditi574 I see that `handleClickCleanScopes` is setting the state to the the initial state. To mitigate duplication, could we do:

```js
export default class ScopesetExpander extends React.PureComponent {
  initialState = {
    scopes: [],
    expandedScopes: null,
    error: null,
    scopesIsValid: false
  };
 
  state = this.initialState;

  //   ...

  handleClickCleanScopes = () => {
    this.setState(this.initialState);
  };

  // ...
```

**Comment by Aditi574** [comment]
@helfi92 yes you're right! Let me make the changes.

**Comment by helfi92** [comment]
@Aditi574 I think your change was only pushed to your fork but not here.

**Comment by Aditi574** [comment]
@helfi92 I created a new PR #458 after making the changes. Is that incorrect?

**Comment by helfi92** [comment]
In the future, it's better to push your changes to the same pull-request. I'll close this pull-request for now and we can carry on in #458.

**Pull request closed without merging**
