### PR TITLE
Add scope intersection feature

### PR DESCRIPTION
**Pull request by helfi92**

### CODE REVIEW

**Comment by helfi92** [comment]
@djmitche I was thinking after we merge this, we could add some type of notification that notifies the user that scopes have been altered to match the scopes he owns. It will remove one layer of confusion.

**Comment by helfi92** [comment]
@djmitche I just saw your email regarding CLI login. Is the scope intersection feature needed right now? I'm asking because of the change freeze. I am trying to see if we should get this merged now or later.

**Comment by djmitche** [comment]
Oh, yes, I thought this had landed already.

**Comment by helfi92** [comment]
@eliperelman Permission to merge?

**Comment by eliperelman** [comment]
I'm merging this since it is a currently-unused feature, hence no risk.

**Pull request merged**
