### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by eliperelman**
This is for branch protection during change freeze.

### CODE REVIEW

**Comment by djmitche** [comment]
You had me until "change freeze".  What will this accomplish?

**Comment by eliperelman** [comment]
It will ensure that code isn't merged unless I review it, since I am actively weighing the risk of merging things into master right now.

**Comment by djmitche** [comment]
Seems like overkill to me, but it doesn't hurt.

**Comment by djmitche** [comment]
I'll defer to greg here.

**Comment by gregarndt** [comment]
Eh, I do agree it might be overkill.  We haven't needed to implement this on the backend side, which is much more risky to make changes that could impact production.

There's nothing wrong with this, so I won't block from landing, I just think it's unnecessary.  Those with permissions to merge to master should understand consequences.

**Pull request merged**
