### PR TITLE
Create a staging provisioner page for tools

### PR DESCRIPTION
**Pull request by jhford**
This is probably not the best way to do it, so I won't be offended if you'd prefer to do it differently.  Now that more people are looking at the provisioner codebase, having a UI for the staging provisioner is more important.  I'd also be OK omitting it from the landing page, but don't have strong thoughts on that.

### CODE REVIEW

**Comment by eliperelman** [comment]
Can you tell me if there is a major difference between the code here and the code in views/AwsProvisioner, other than a few URL changes?

**Comment by jhford** [comment]
I can do even better than saying it :)

```
$ diff -U10 -r src/views/AwsProvisioner{,Staging}
diff -U10 -r src/views/AwsProvisioner/WorkerTypeTable.js src/views/AwsProvisionerStaging/WorkerTypeTable.js
--- src/views/AwsProvisioner/WorkerTypeTable.js	2017-08-09 16:08:17.000000000 +0200
+++ src/views/AwsProvisionerStaging/WorkerTypeTable.js	2017-08-10 15:16:40.000000000 +0200
@@ -82,23 +82,23 @@
       });
     } catch (err) {
       this.setState({
         workerTypeSummaries: null,
         error: err
       });
     }
   }

   setSelected = workerType => this.props.history
-    .replace(`/aws-provisioner/${workerType}/${this.props.currentTab}`);
+    .replace(`/aws-provisioner-staging/${workerType}/${this.props.currentTab}`);

-  handleTabChange = tab => this.props.history.replace(`/aws-provisioner/${this.props.workerType}/${tab}`);
+  handleTabChange = tab => this.props.history.replace(`/aws-provisioner-staging/${this.props.workerType}/${tab}`);

   workerTypeCreated = async (workerType) => {
     await this.loadWorkerTypeSummaries();

     this.setSelected(workerType);
   };

   // work around https://github.com/taskcluster/aws-provisioner/pull/70
   updateSummary = (workerType, summary) => this.setState({
     workerTypeSummaries: this.state.workerTypeSummaries
diff -U10 -r src/views/AwsProvisioner/index.js src/views/AwsProvisionerStaging/index.js
--- src/views/AwsProvisioner/index.js	2017-08-09 16:08:17.000000000 +0200
+++ src/views/AwsProvisionerStaging/index.js	2017-08-09 16:11:24.000000000 +0200
@@ -1,29 +1,29 @@
 import React from 'react';
 import { Redirect } from 'react-router-dom';
 import Clients from '../../components/Clients';
 import WorkerTypeTable from './WorkerTypeTable';

 const View = ({ credentials, match, history, location }) => {
   const [worker, tab] = location.hash.slice(1).split('/');

   if (worker && tab) {
-    return <Redirect to={`/aws-provisioner/${worker}/${tab}`} />;
+    return <Redirect to={`/aws-provisioner-staging/${worker}/${tab}`} />;
   } else if (worker) {
-    return <Redirect to={`/aws-provisioner/${worker}`} />;
+    return <Redirect to={`/aws-provisioner-staging/${worker}`} />;
   }

   return (
-    <Clients credentials={credentials} Queue AwsProvisioner={{ baseUrl: 'https://aws-provisioner.taskcluster.net/v1' }}>
+    <Clients credentials={credentials} Queue AwsProvisioner={{ baseUrl: 'https://provisioner-staging.herokuapp.com/v1/' }}>
       {clients => (
         <WorkerTypeTable
           {...clients}
           history={history}
-          provisionerId="aws-provisioner-v1"
+          provisionerId="staging-aws"
           workerType={match.params.workerType}
           currentTab={match.params.currentTab} />
       )}
     </Clients>
   );
 };

 export default View;
```

**Comment by eliperelman** [comment]
😮 that's awesome, gonna have to remember that!

I'm thinking we could probably make this easier by passing some props from the routing. Give me a sec and I think I can whip up a quick snippet.

**Comment by eliperelman** [comment]
What if we passed these props via the routing:

```jsx
<PropsRoute
  path="/aws-provisioner/:workerType?/:currentTab?"
  routeRoot="/aws-provisioner"
  baseUrl="https://aws-provisioner.taskcluster.net/v1"
  provisionerId="aws-provisioner-v1"
  component={AwsProvisioner}
  credentials={credentials} />
<PropsRoute
  path="/aws-provisioner-staging/:workerType?/:currentTab?"
  routeRoot="/aws-provisioner-staging"
  baseUrl="https://provisioner-staging.herokuapp.com/v1"
  provisionerId="staging-aws"
  component={AwsProvisioner}
  credentials={credentials} />
```

Then we use the same component, but now can pass these as props to the Client creator and the UI component:

```jsx
const View = ({ credentials, match, history, location, baseUrl, provisionerId, routeRoot }) => {
  const [worker, tab] = location.hash.slice(1).split('/');

  if (worker && tab) {
    return <Redirect to={`${routeRoot}/${worker}/${tab}`} />;
  } else if (worker) {
    return <Redirect to={`${routeRoot}/${worker}`} />;
   }

   return (
    <Clients credentials={credentials} Queue AwsProvisioner={{ baseUrl }}>
       {clients => (
         <WorkerTypeTable
           {...clients}
           history={history}
           routeRoot={routeRoot}
           provisionerId={provisionerId}
           workerType={match.params.workerType}
           currentTab={match.params.currentTab} />
       )}
     </Clients>
   );
 };
```

Then the last thing would just be changing the internals of the AwsProvisioner components to use `this.props.routeRoot` instead of `/aws-provisioner` or `/aws-provisioner-staging`. Sound good?

**Comment by eliperelman** [comment]
@jhford can you try this out and let me know how it works?

**Comment by jhford** [comment]
It seems to work well

**Comment by eliperelman** [comment]
:shipit:

**Pull request merged**
