### PR TITLE
default to the 'tutorial' workerTypes

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by jonasfj** [comment]
Nice...

So just FYI, downside of this is that there is never a "tutorial" worker type ready, which gives people a bad experience as the task isn't running immediately..

**Comment by jonasfj** [comment]
r+

If you want it... I see both ups and downs to doing this...

**Comment by djmitche** [comment]
I think we can add a sentence to the tutorial about that.

**Comment by djmitche** [comment]
I added a note to docs

**Pull request merged**
